//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressiveAnnotations.MvcWebSample {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpressiveAnnotations.MvcWebSample.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree for contact.
        /// </summary>
        public static string AgreeForContact {
            get {
                return ResourceManager.GetString("AgreeForContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to authorize us to contact you..
        /// </summary>
        public static string AgreeForContactRequired {
            get {
                return ResourceManager.GetString("AgreeForContactRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertion for {0} field is not satisfied by the following logic: {1}..
        /// </summary>
        public static string AssertionNotSatisfied {
            get {
                return ResourceManager.GetString("AssertionNotSatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am aware of the possible risks.
        /// </summary>
        public static string AwareOfTheRisks {
            get {
                return ResourceManager.GetString("AwareOfTheRisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are required to agree that you are aware of the risks of travel..
        /// </summary>
        public static string AwareOfTheRisksRequired {
            get {
                return ResourceManager.GetString("AwareOfTheRisksRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood type.
        /// </summary>
        public static string BloodType {
            get {
                return ResourceManager.GetString("BloodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood type is required if you do extreme sports, or if you do any type of sport and plan to go abroad..
        /// </summary>
        public static string BloodTypeRequired {
            get {
                return ResourceManager.GetString("BloodTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not enter any contact information. At least e-mail or phone should be provided..
        /// </summary>
        public static string EmailOrPhoneRequired {
            get {
                return ResourceManager.GetString("EmailOrPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme.
        /// </summary>
        public static string Extreme {
            get {
                return ResourceManager.GetString("Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required by the following logic: {1}..
        /// </summary>
        public static string FieldConditionallyRequired {
            get {
                return ResourceManager.GetString("FieldConditionallyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        public static string France {
            get {
                return ResourceManager.GetString("France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are afraid that going back to the past is not an option nowadays..
        /// </summary>
        public static string FutureDateRequired {
            get {
                return ResourceManager.GetString("FutureDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        public static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am going abroad.
        /// </summary>
        public static string GoAbroad {
            get {
                return ResourceManager.GetString("GoAbroad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediate contact.
        /// </summary>
        public static string ImmediateContact {
            get {
                return ResourceManager.GetString("ImmediateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shall we contact immidiately?.
        /// </summary>
        public static string ImmediateContactRequired {
            get {
                return ResourceManager.GetString("ImmediateContactRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest suggested return.
        /// </summary>
        public static string LatestSuggestedReturnDate {
            get {
                return ResourceManager.GetString("LatestSuggestedReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next country.
        /// </summary>
        public static string NextCountry {
            get {
                return ResourceManager.GetString("NextCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport number.
        /// </summary>
        public static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poland.
        /// </summary>
        public static string Poland {
            get {
                return ResourceManager.GetString("Poland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Political stability.
        /// </summary>
        public static string PoliticalStability {
            get {
                return ResourceManager.GetString("PoliticalStability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for such a long travel.
        /// </summary>
        public static string ReasonForLongTravel {
            get {
                return ResourceManager.GetString("ReasonForLongTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you plan to stay abroad longer than one month from now, write down your reasons..
        /// </summary>
        public static string ReasonForLongTravelRequired {
            get {
                return ResourceManager.GetString("ReasonForLongTravelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasons for travel.
        /// </summary>
        public static string ReasonForTravel {
            get {
                return ResourceManager.GetString("ReasonForTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you plan to go abroad and you are between 25 and 55 or plan to visit the same foreign country twice, write down your reasons..
        /// </summary>
        public static string ReasonForTravelRequired {
            get {
                return ResourceManager.GetString("ReasonForTravelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return date.
        /// </summary>
        public static string ReturnDate {
            get {
                return ResourceManager.GetString("ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree for contact.
        /// </summary>
        public static string SpamAllowed {
            get {
                return ResourceManager.GetString("SpamAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do not agree for contact.
        /// </summary>
        public static string SpamForbidden {
            get {
                return ResourceManager.GetString("SpamForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports you like the most.
        /// </summary>
        public static string SportType {
            get {
                return ResourceManager.GetString("SportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncertain.
        /// </summary>
        public static string Uncertain {
            get {
                return ResourceManager.GetString("Uncertain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
